services:
  siem:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "
      until nc -z postgres 5432; do sleep 1; done &&
      bunx prisma db push &&
      bun start"
    depends_on:
      - elasticsearch
      - postgres
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '0.50'

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  esdata:
    driver: local
  kdata:
    driver: local
  postgres:
    driver: local
